[build]
# command = "git submodule update --init --remote && gem install bundler && bundle install && bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
command = "ls _external/data && git submodule status"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2" 

[dev]
publish = "_site"
framework = "#static"

[[redirects]]
  from = "/"
  to = "/standards-guidelines/linking/"
